description = 'Compiles the exact JVM examples displayed by the Vireo Starter Storybook. Never published.'

dependencies {
    implementation project(':vireo-core')
    implementation project(':vireo-auth')
    implementation project(':vireo-history')
    implementation project(':vireo-query')
    implementation project(':vireo-offline')
    implementation 'org.springframework.security:spring-security-ldap'
}
